name: Generate Release logs
on:
  push:
    branches:
      - "release/**"

      # exclude bot pushes to avoid infinite loop
    paths-ignore:
      - 'sample_action.yml'
jobs:
  watch-changes-in-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Create File
        run: echo "Hello, World!" > example.txt
      - name: Commit Files
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"
          git add .
          git commit -m "Add example.txt"
      - name: Push Changes
         uses: ad-m/github-push-action@main
        with:
          branch: main
  